#!/bin/sh

echo "- making sure the system clock is sane"

# If the system clock is before the source date, then we know it's
# incorrect and set it too the source date. However, to account for
# potential issues due to timezone differences etc we ignore clocks
# that are up to 1 day before the source date.
SECS_OF_DAY=86400
. /etc/os-release
SOURCE_DATE="$TAILS_SOURCE_DATE_EPOCH"
if [ "$(date +%s)" -lt $((SOURCE_DATE-SECS_OF_DAY)) ]; then
    date --set "@${SOURCE_DATE}"
fi
