[[commands]]
executable = "/usr/local/lib/tails-run-tor-browser-in-flatpak"
allowed_user = "amnesia"
[commands.env_keep]
value = ["ENVFILE"]
reason = "FIXME: next time you have the problem space in mind, e.g. if you edit this file, explain why this is needed *and* safe. For details, see tails/tails#20863."
[commands.arbitrary_arguments]
value = true
reason = "run-tor-browser will validate arguments to reject options (see tails/tails#19595)"
