raw_block = """
# Allow the privileged tails-persistent-storage user to use the
# --close-from option which is needed to close all file descriptors
# except for the ones we want to pass to tps.
Defaults:tails-persistent-storage closefrom_override

# Allow the privileged tails-persistent-storage user to run commands as
# the amnesia user, so that it can run the tps-frontend script as
# amnesia.
tails-persistent-storage   ALL = (amnesia)    NOPASSWD: ALL
"""

[[commands]]
# Allow amnesia to run /usr/local/bin/tails-persistent-storage as the
# privileged tails-persistent-storage user. This is needed to connect
# to the tps D-Bus service. See
# config/chroot_local-includes/usr/local/bin/tails-persistent-storage
# for details.
executable = "/usr/local/bin/tails-persistent-storage"
allowed_user = "amnesia"
run_as_user = "tails-persistent-storage"
[commands.env_keep]
value = ["ENVFILE"]
reason = "FIXME: next time you have the problem space in mind, e.g. if you edit this file, explain why this is needed *and* safe. For details, see tails/tails#20863."
