[[commands]]
allowed_user = "amnesia"
executable = "/usr/local/bin/whisperback"
[commands.arbitrary_arguments]
value = true
reason = "config/chroot_local-includes/usr/local/bin/whisperback validates arguments"
